---
- name: "Configure F5: DNS setting"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  roles:
    - role: f5devcentral.f5ansible

  tasks:
    - name: Ensure state of DNS settings on the BIG-IP
      bigip_device_dns:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        hostname: "{{ inventory_hostname }}"
        name_servers: "{{ bigip_device_dns_name_servers | default(omit) }}"
        search: "{{ bigip_device_dns_searchs | default(omit) }}"
