---
- name: "Configure F5: Selfips on interfaces"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  tasks:
    - name: Ensure selfip address on interfaces
      bigip_selfip:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        partition: "{{ bigip_partition | default(omit) }}"
        name:  "{{ bigip_selfip_name }}"
        address: "{{ bigip_selfip_ipv4_address | ipaddr('address') }}"
        netmask: "{{ bigip_selfip_ipv4_netmask | ipaddr('netmask') }}"
        vlan: "{{ bigip_selfip_vlan }}"